
import { Category, Position, WordData } from './types';

export const GAME_LIBRARY: Record<Category, Record<Position, WordData[]>> = {
  directas: {
    inicio: [
        { word: "casa", emoji: "🏠", syllables: ["ca", "sa"], targetIdx: 0, options: ["ca", "ka"] },
        { word: "pato", emoji: "🦆", syllables: ["pa", "to"], targetIdx: 0, options: ["pa", "ba"] },
        { word: "mono", emoji: "🐒", syllables: ["mo", "no"], targetIdx: 0, options: ["mo", "no"] },
        { word: "luna", emoji: "🌙", syllables: ["lu", "na"], targetIdx: 0, options: ["lu", "lo"] },
        { word: "sapo", emoji: "🐸", syllables: ["sa", "po"], targetIdx: 0, options: ["sa", "za"] },
        { word: "dedo", emoji: "☝️", syllables: ["de", "do"], targetIdx: 0, options: ["de", "be"] },
        { word: "vaca", emoji: "🐮", syllables: ["va", "ca"], targetIdx: 0, options: ["va", "ba"] },
        { word: "gato", emoji: "🐱", syllables: ["ga", "to"], targetIdx: 0, options: ["ga", "ja"] },
        { word: "foca", emoji: "🦭", syllables: ["fo", "ca"], targetIdx: 0, options: ["fo", "po"] },
        { word: "nube", emoji: "☁️", syllables: ["nu", "be"], targetIdx: 0, options: ["nu", "mu"] },
        { word: "pino", emoji: "🌲", syllables: ["pi", "no"], targetIdx: 0, options: ["pi", "bi"] },
        { word: "rosa", emoji: "🌹", syllables: ["ro", "sa"], targetIdx: 0, options: ["ro", "lo"] },
        { word: "toro", emoji: "🐂", syllables: ["to", "ro"], targetIdx: 0, options: ["to", "do"] },
        { word: "rana", emoji: "🐸", syllables: ["ra", "na"], targetIdx: 0, options: ["ra", "la"] },
        { word: "pala", emoji: "🧹", syllables: ["pa", "la"], targetIdx: 0, options: ["pa", "ta"] },
        { word: "nido", emoji: "🪺", syllables: ["ni", "do"], targetIdx: 0, options: ["ni", "mi"] },
        { word: "bola", emoji: "⚽", syllables: ["bo", "la"], targetIdx: 0, options: ["bo", "po"] },
        { word: "jarrón", emoji: "🏺", syllables: ["ja", "rrón"], targetIdx: 0, options: ["ja", "ga"] },
        { word: "silla", emoji: "🪑", syllables: ["si", "lla"], targetIdx: 0, options: ["si", "zi"] },
        { word: "piña", emoji: "🍍", syllables: ["pi", "ña"], targetIdx: 0, options: ["pi", "bi"] }
    ],
    mitad: [
        { word: "pelota", emoji: "⚽", syllables: ["pe", "lo", "ta"], targetIdx: 1, options: ["lo", "ro"] },
        { word: "maleta", emoji: "💼", syllables: ["ma", "le", "ta"], targetIdx: 1, options: ["le", "de"] },
        { word: "comida", emoji: "🍽️", syllables: ["co", "mi", "da"], targetIdx: 1, options: ["mi", "ni"] },
        { word: "canica", emoji: "⚪", syllables: ["ca", "ni", "ca"], targetIdx: 1, options: ["ni", "mi"] },
        { word: "paloma", emoji: "🕊️", syllables: ["pa", "lo", "ma"], targetIdx: 1, options: ["lo", "ro"] },
        { word: "basura", emoji: "🗑️", syllables: ["ba", "su", "ra"], targetIdx: 1, options: ["su", "zu"] },
        { word: "cocina", emoji: "🍳", syllables: ["co", "ci", "na"], targetIdx: 1, options: ["ci", "si"] },
        { word: "madera", emoji: "🪵", syllables: ["ma", "de", "ra"], targetIdx: 1, options: ["de", "be"] },
        { word: "tomate", emoji: "🍅", syllables: ["to", "ma", "te"], targetIdx: 1, options: ["ma", "na"] },
        { word: "raqueta", emoji: "🎾", syllables: ["ra", "que", "ta"], targetIdx: 1, options: ["que", "ke"] },
        { word: "zapato", emoji: "👟", syllables: ["za", "pa", "to"], targetIdx: 1, options: ["pa", "ba"] },
        { word: "abanico", emoji: "🪭", syllables: ["a", "ba", "ni", "co"], targetIdx: 2, options: ["ni", "mi"] },
        { word: "corona", emoji: "👑", syllables: ["co", "ro", "na"], targetIdx: 1, options: ["ro", "lo"] },
        { word: "pecera", emoji: "🥣", syllables: ["pe", "ce", "ra"], targetIdx: 1, options: ["ce", "se"] },
        { word: "jirafa", emoji: "🦒", syllables: ["ji", "ra", "fa"], targetIdx: 1, options: ["ra", "la"] },
        { word: "pepino", emoji: "🥒", syllables: ["pe", "pi", "no"], targetIdx: 1, options: ["pi", "bi"] },
        { word: "conejo", emoji: "🐇", syllables: ["co", "ne", "jo"], targetIdx: 1, options: ["ne", "me"] },
        { word: "camino", emoji: "🛣️", syllables: ["ca", "mi", "no"], targetIdx: 1, options: ["mi", "ni"] },
        { word: "regalo", emoji: "🎁", syllables: ["re", "ga", "lo"], targetIdx: 1, options: ["ga", "ja"] },
        { word: "capote", emoji: "🧥", syllables: ["ca", "po", "te"], targetIdx: 1, options: ["po", "bo"] }
    ],
    final: [
        { word: "bota", emoji: "🥾", syllables: ["bo", "ta"], targetIdx: 1, options: ["ta", "da"] },
        { word: "luna", emoji: "🌙", syllables: ["lu", "na"], targetIdx: 1, options: ["na", "ma"] },
        { word: "gato", emoji: "🐱", syllables: ["ga", "to"], targetIdx: 1, options: ["to", "do"] },
        { word: "sapo", emoji: "🐸", syllables: ["sa", "po"], targetIdx: 1, options: ["po", "bo"] },
        { word: "vaca", emoji: "🐮", syllables: ["va", "ca"], targetIdx: 1, options: ["ca", "ga"] },
        { word: "dedo", emoji: "☝️", syllables: ["de", "do"], targetIdx: 1, options: ["do", "bo"] },
        { word: "piña", emoji: "🍍", syllables: ["pi", "ña"], targetIdx: 1, options: ["ña", "ma"] },
        { word: "rosa", emoji: "🌹", syllables: ["ro", "sa"], targetIdx: 1, options: ["sa", "za"] },
        { word: "bola", emoji: "⚽", syllables: ["bo", "la"], targetIdx: 1, options: ["la", "ra"] },
        { word: "pala", emoji: "🧹", syllables: ["pa", "la"], targetIdx: 1, options: ["la", "na"] },
        { word: "nube", emoji: "☁️", syllables: ["nu", "be"], targetIdx: 1, options: ["be", "pe"] },
        { word: "pera", emoji: "🍐", syllables: ["pe", "ra"], targetIdx: 1, options: ["ra", "la"] },
        { word: "lobo", emoji: "🐺", syllables: ["lo", "bo"], targetIdx: 1, options: ["bo", "po"] },
        { word: "toro", emoji: "🐂", syllables: ["to", "ro"], targetIdx: 1, options: ["ro", "lo"] },
        { word: "foca", emoji: "🦭", syllables: ["fo", "ca"], targetIdx: 1, options: ["ca", "ka"] },
        { word: "mesa", emoji: "🪑", syllables: ["me", "sa"], targetIdx: 1, options: ["sa", "za"] },
        { word: "casa", emoji: "🏠", syllables: ["ca", "sa"], targetIdx: 1, options: ["sa", "za"] },
        { word: "moto", emoji: "🏍️", syllables: ["mo", "to"], targetIdx: 1, options: ["to", "do"] },
        { word: "rana", emoji: "🐸", syllables: ["ra", "na"], targetIdx: 1, options: ["na", "la"] },
        { word: "copa", emoji: "🍷", syllables: ["co", "pa"], targetIdx: 1, options: ["pa", "ba"] }
    ]
  },
  inversas: {
    inicio: [
        { word: "árbol", emoji: "🌳", syllables: ["ár", "bol"], targetIdx: 0, options: ["ár", "ra"] },
        { word: "isla", emoji: "🏝️", syllables: ["is", "la"], targetIdx: 0, options: ["is", "si"] },
        { word: "espejo", emoji: "🪞", syllables: ["es", "pe", "jo"], targetIdx: 0, options: ["es", "se"] },
        { word: "antena", emoji: "📡", syllables: ["an", "te", "na"], targetIdx: 0, options: ["an", "na"] },
        { word: "indio", emoji: "🏹", syllables: ["in", "dio"], targetIdx: 0, options: ["in", "ni"] },
        { word: "escoba", emoji: "🧹", syllables: ["es", "co", "ba"], targetIdx: 0, options: ["es", "se"] },
        { word: "ángel", emoji: "👼", syllables: ["án", "gel"], targetIdx: 0, options: ["án", "na"] },
        { word: "arco", emoji: "🏹", syllables: ["ar", "co"], targetIdx: 0, options: ["ar", "ra"] },
        { word: "elfo", emoji: "🧝", syllables: ["el", "fo"], targetIdx: 0, options: ["el", "le"] },
        { word: "iglú", emoji: "🧊", syllables: ["ig", "lú"], targetIdx: 0, options: ["ig", "gi"] },
        { word: "olla", emoji: "🍲", syllables: ["o", "lla"], targetIdx: 0, options: ["o", "u"] },
        { word: "aspa", emoji: "✖️", syllables: ["as", "pa"], targetIdx: 0, options: ["as", "sa"] },
        { word: "imán", emoji: "🧲", syllables: ["i", "mán"], targetIdx: 0, options: ["i", "e"] },
        { word: "urna", emoji: "🗳️", syllables: ["ur", "na"], targetIdx: 0, options: ["ur", "ru"] },
        { word: "enano", emoji: "🍄", syllables: ["e", "na", "no"], targetIdx: 0, options: ["e", "a"] },
        { word: "ojo", emoji: "👁️", syllables: ["o", "jo"], targetIdx: 0, options: ["o", "i"] },
        { word: "uva", emoji: "🍇", syllables: ["u", "va"], targetIdx: 0, options: ["u", "o"] },
        { word: "oso", emoji: "🐻", syllables: ["o", "so"], targetIdx: 0, options: ["o", "e"] },
        { word: "espía", emoji: "🕵️", syllables: ["es", "pí", "a"], targetIdx: 0, options: ["es", "se"] },
        { word: "alto", emoji: "⬆️", syllables: ["al", "to"], targetIdx: 0, options: ["al", "la"] }
    ],
    mitad: [
        { word: "antorcha", emoji: "🔦", syllables: ["an", "tor", "cha"], targetIdx: 1, options: ["tor", "tro"] },
        { word: "ventana", emoji: "🪟", syllables: ["ven", "ta", "na"], targetIdx: 0, options: ["ven", "ne"] },
        { word: "martillo", emoji: "🔨", syllables: ["mar", "ti", "llo"], targetIdx: 0, options: ["mar", "ram"] },
        { word: "pincel", emoji: "🖌️", syllables: ["pin", "cel"], targetIdx: 1, options: ["cel", "ce"] },
        { word: "castillo", emoji: "🏰", syllables: ["cas", "ti", "llo"], targetIdx: 0, options: ["cas", "sac"] },
        { word: "serpiente", emoji: "🐍", syllables: ["ser", "pien", "te"], targetIdx: 0, options: ["ser", "res"] },
        { word: "montaña", emoji: "⛰️", syllables: ["mon", "ta", "ña"], targetIdx: 0, options: ["mon", "nom"] },
        { word: "bufanda", emoji: "🧣", syllables: ["bu", "fan", "da"], targetIdx: 1, options: ["fan", "naf"] },
        { word: "pintura", emoji: "🎨", syllables: ["pin", "tu", "ra"], targetIdx: 0, options: ["pin", "nip"] },
        { word: "volcán", emoji: "🌋", syllables: ["vol", "cán"], targetIdx: 0, options: ["vol", "lov"] },
        { word: "sandía", emoji: "🍉", syllables: ["san", "dí", "a"], targetIdx: 0, options: ["san", "nas"] },
        { word: "duende", emoji: "🧚", syllables: ["duen", "de"], targetIdx: 0, options: ["duen", "den"] },
        { word: "fuente", emoji: "⛲", syllables: ["fuen", "te"], targetIdx: 0, options: ["fuen", "nef"] },
        { word: "diente", emoji: "🦷", syllables: ["dien", "te"], targetIdx: 0, options: ["dien", "ned"] },
        { word: "puente", emoji: "🌉", syllables: ["puen", "te"], targetIdx: 0, options: ["puen", "nep"] },
        { word: "espada", emoji: "⚔️", syllables: ["es", "pa", "da"], targetIdx: 0, options: ["es", "se"] },
        { word: "alfombra", emoji: "🧶", syllables: ["al", "fom", "bra"], targetIdx: 1, options: ["fom", "mof"] },
        { word: "perla", emoji: "🦪", syllables: ["per", "la"], targetIdx: 0, options: ["per", "pre"] },
        { word: "barco", emoji: "🚢", syllables: ["bar", "co"], targetIdx: 0, options: ["bar", "bra"] },
        { word: "selva", emoji: "🌿", syllables: ["sel", "va"], targetIdx: 0, options: ["sel", "les"] }
    ],
    final: [
        { word: "tambor", emoji: "🥁", syllables: ["tam", "bor"], targetIdx: 1, options: ["bor", "bro"] },
        { word: "pastel", emoji: "🍰", syllables: ["pas", "tel"], targetIdx: 1, options: ["tel", "tle"] },
        { word: "papel", emoji: "📄", syllables: ["pa", "pel"], targetIdx: 1, options: ["pel", "ple"] },
        { word: "ratón", emoji: "🐭", syllables: ["ra", "tón"], targetIdx: 1, options: ["tón", "not"] },
        { word: "limón", emoji: "🍋", syllables: ["li", "món"], targetIdx: 1, options: ["món", "nom"] },
        { word: "melón", emoji: "🍈", syllables: ["me", "lón"], targetIdx: 1, options: ["lón", "nol"] },
        { word: "balcón", emoji: "🏙️", syllables: ["bal", "cón"], targetIdx: 1, options: ["cón", "noc"] },
        { word: "botón", emoji: "🔘", syllables: ["bo", "tón"], targetIdx: 1, options: ["tón", "not"] },
        { word: "avión", emoji: "✈️", syllables: ["a", "vión"], targetIdx: 1, options: ["vión", "niv"] },
        { word: "camión", emoji: "🚚", syllables: ["ca", "mión"], targetIdx: 1, options: ["mión", "nim"] },
        { word: "jamón", emoji: "🍖", syllables: ["ja", "món"], targetIdx: 1, options: ["món", "nom"] },
        { word: "jabón", emoji: "🧼", syllables: ["ja", "bón"], targetIdx: 1, options: ["bón", "nob"] },
        { word: "sillón", emoji: "🛋️", syllables: ["si", "llón"], targetIdx: 1, options: ["llón", "nol"] },
        { word: "bastón", emoji: "🦯", syllables: ["bas", "tón"], targetIdx: 1, options: ["tón", "not"] },
        { word: "delfín", emoji: "🐬", syllables: ["del", "fín"], targetIdx: 1, options: ["fín", "nif"] },
        { word: "jardín", emoji: "🏡", syllables: ["jar", "dín"], targetIdx: 1, options: ["dín", "nid"] },
        { word: "patín", emoji: "🛼", syllables: ["pa", "tín"], targetIdx: 1, options: ["tín", "nit"] },
        { word: "pantalón", emoji: "👖", syllables: ["pan", "ta", "lón"], targetIdx: 2, options: ["lón", "nol"] },
        { word: "dormir", emoji: "💤", syllables: ["dor", "mir"], targetIdx: 1, options: ["mir", "rim"] },
        { word: "comer", emoji: "🍴", syllables: ["co", "mer"], targetIdx: 1, options: ["mer", "rem"] }
    ]
  },
  trabadas: {
    inicio: [
        { word: "brazo", emoji: "💪", syllables: ["bra", "zo"], targetIdx: 0, options: ["bra", "bar"] },
        { word: "globo", emoji: "🎈", syllables: ["glo", "bo"], targetIdx: 0, options: ["glo", "gol"] },
        { word: "tren", emoji: "🚂", syllables: ["tren"], targetIdx: 0, options: ["tren", "ter"] },
        { word: "fresa", emoji: "🍓", syllables: ["fre", "sa"], targetIdx: 0, options: ["fre", "fer"] },
        { word: "grifo", emoji: "🚰", syllables: ["gri", "fo"], targetIdx: 0, options: ["gri", "gir"] },
        { word: "plato", emoji: "🍽️", syllables: ["pla", "to"], targetIdx: 0, options: ["pla", "pal"] },
        { word: "bruja", emoji: "🧙", syllables: ["bru", "ja"], targetIdx: 0, options: ["bru", "bur"] },
        { word: "clavo", emoji: "🔨", syllables: ["cla", "vo"], targetIdx: 0, options: ["cla", "cal"] },
        { word: "dragón", emoji: "🐲", syllables: ["dra", "gón"], targetIdx: 0, options: ["dra", "dar"] },
        { word: "fruta", emoji: "🍎", syllables: ["fru", "ta"], targetIdx: 0, options: ["fru", "fur"] },
        { word: "granja", emoji: "🚜", syllables: ["gran", "ja"], targetIdx: 0, options: ["gran", "gar"] },
        { word: "preso", emoji: "⛓️", syllables: ["pre", "so"], targetIdx: 0, options: ["pre", "per"] },
        { word: "trino", emoji: "🐦", syllables: ["tri", "no"], targetIdx: 0, options: ["tri", "tir"] },
        { word: "blanco", emoji: "⚪", syllables: ["blan", "co"], targetIdx: 0, options: ["blan", "bal"] },
        { word: "flaco", emoji: "🦴", syllables: ["fla", "co"], targetIdx: 0, options: ["fla", "fal"] },
        { word: "gloria", emoji: "🏆", syllables: ["glo", "ria"], targetIdx: 0, options: ["glo", "gol"] },
        { word: "pluma", emoji: "🪶", syllables: ["plu", "ma"], targetIdx: 0, options: ["plu", "pul"] },
        { word: "crema", emoji: "🧴", syllables: ["cre", "ma"], targetIdx: 0, options: ["cre", "cer"] },
        { word: "cruz", emoji: "✝️", syllables: ["cruz"], targetIdx: 0, options: ["cruz", "curz"] },
        { word: "flecha", emoji: "🏹", syllables: ["fle", "cha"], targetIdx: 0, options: ["fle", "fel"] }
    ],
    mitad: [
        { word: "libreta", emoji: "📓", syllables: ["li", "bre", "ta"], targetIdx: 1, options: ["bre", "ber"] },
        { word: "estrella", emoji: "⭐", syllables: ["es", "tre", "lla"], targetIdx: 1, options: ["tre", "ter"] },
        { word: "escribir", emoji: "✍️", syllables: ["es", "cri", "bir"], targetIdx: 1, options: ["cri", "cir"] },
        { word: "ombligo", emoji: "🔘", syllables: ["om", "bli", "go"], targetIdx: 1, options: ["bli", "bil"] },
        { word: "sobrino", emoji: "🧒", syllables: ["so", "bri", "no"], targetIdx: 1, options: ["bri", "bir"] },
        { word: "madrina", emoji: "✨", syllables: ["ma", "dri", "na"], targetIdx: 1, options: ["dri", "dir"] },
        { word: "padrino", emoji: "🤵", syllables: ["pa", "dri", "no"], targetIdx: 1, options: ["dri", "dir"] },
        { word: "refresco", emoji: "🥤", syllables: ["re", "fres", "co"], targetIdx: 1, options: ["fres", "fers"] },
        { word: "recreo", emoji: "🛝", syllables: ["re", "cre", "o"], targetIdx: 1, options: ["cre", "cer"] },
        { word: "sorpresa", emoji: "🎉", syllables: ["sor", "pre", "sa"], targetIdx: 1, options: ["pre", "per"] },
        { word: "vinagre", emoji: "🧪", syllables: ["vi", "na", "gre"], targetIdx: 2, options: ["gre", "ger"] },
        { word: "potrero", emoji: "🐎", syllables: ["po", "tre", "ro"], targetIdx: 1, options: ["tre", "ter"] },
        { word: "tablero", emoji: "🏁", syllables: ["ta", "ble", "ro"], targetIdx: 1, options: ["ta", "ble"] },
        { word: "granizo", emoji: "🌨️", syllables: ["gra", "ni", "zo"], targetIdx: 0, options: ["gra", "gar"] },
        { word: "abrazo", emoji: "🫂", syllables: ["a", "bra", "zo"], targetIdx: 1, options: ["bra", "bar"] },
        { word: "refrán", emoji: "📜", syllables: ["re", "frán"], targetIdx: 1, options: ["frán", "far"] },
        { word: "aplauso", emoji: "👏", syllables: ["a", "plau", "so"], targetIdx: 1, options: ["plau", "pal"] },
        { word: "ciclista", emoji: "🚴", syllables: ["ci", "clis", "ta"], targetIdx: 1, options: ["clis", "cal"] },
        { word: "soplar", emoji: "🌬️", syllables: ["so", "plar"], targetIdx: 1, options: ["plar", "pal"] },
        { word: "copla", emoji: "🎶", syllables: ["co", "pla"], targetIdx: 1, options: ["pla", "pal"] }
    ],
    final: [
        { word: "tigre", emoji: "🐯", syllables: ["ti", "gre"], targetIdx: 1, options: ["gre", "ger"] },
        { word: "cofre", emoji: "🏴‍☠️", syllables: ["co", "fre"], targetIdx: 1, options: ["fre", "fer"] },
        { word: "sobre", emoji: "✉️", syllables: ["so", "bre"], targetIdx: 1, options: ["bre", "ber"] },
        { word: "cabra", emoji: "🐐", syllables: ["ca", "bra"], targetIdx: 1, options: ["bra", "bar"] },
        { word: "cebra", emoji: "🦓", syllables: ["ce", "bra"], targetIdx: 1, options: ["bra", "bar"] },
        { word: "madre", emoji: "👩", syllables: ["ma", "dre"], targetIdx: 1, options: ["dre", "der"] },
        { word: "padre", emoji: "👨", syllables: ["pa", "dre"], targetIdx: 1, options: ["dre", "der"] },
        { word: "sangre", emoji: "🩸", syllables: ["san", "gre"], targetIdx: 1, options: ["gre", "ger"] },
        { word: "mugre", emoji: "🧼", syllables: ["mu", "gre"], targetIdx: 1, options: ["gre", "ger"] },
        { word: "pupitre", emoji: "🪑", syllables: ["pu", "pi", "tre"], targetIdx: 2, options: ["tre", "ter"] },
        { word: "sastre", emoji: "🧵", syllables: ["sas", "tre"], targetIdx: 1, options: ["tre", "ter"] },
        { word: "postre", emoji: "🍰", syllables: ["pos", "tre"], targetIdx: 1, options: ["tre", "ter"] },
        { word: "buitre", emoji: "🦅", syllables: ["bui", "tre"], targetIdx: 1, options: ["tre", "ter"] },
        { word: "liebre", emoji: "🐇", syllables: ["lie", "bre"], targetIdx: 1, options: ["bre", "ber"] },
        { word: "cobre", emoji: "🥉", syllables: ["co", "bre"], targetIdx: 1, options: ["bre", "ber"] },
        { word: "soplo", emoji: "🌬️", syllables: ["so", "plo"], targetIdx: 1, options: ["plo", "pol"] },
        { word: "acople", emoji: "🔌", syllables: ["a", "co", "ple"], targetIdx: 2, options: ["ple", "pel"] },
        { word: "noble", emoji: "👑", syllables: ["no", "ble"], targetIdx: 1, options: ["ble", "bel"] },
        { word: "cable", emoji: "🔌", syllables: ["ca", "ble"], targetIdx: 1, options: ["ble", "bel"] },
        { word: "mueble", emoji: "🛏️", syllables: ["mue", "ble"], targetIdx: 1, options: ["ble", "bel"] }
    ]
  },
  mixtas: {
    inicio: [
        { word: "barco", emoji: "🚢", syllables: ["bar", "co"], targetIdx: 0, options: ["bar", "bra"] },
        { word: "tarta", emoji: "🎂", syllables: ["tar", "ta"], targetIdx: 0, options: ["tar", "tra"] },
        { word: "selva", emoji: "🌿", syllables: ["sel", "va"], targetIdx: 0, options: ["sel", "les"] },
        { word: "carpa", emoji: "⛺", syllables: ["car", "pa"], targetIdx: 0, options: ["car", "cra"] },
        { word: "cerdo", emoji: "🐷", syllables: ["cer", "do"], targetIdx: 0, options: ["cer", "cre"] },
        { word: "dardo", emoji: "🎯", syllables: ["dar", "do"], targetIdx: 0, options: ["dar", "dra"] },
        { word: "gordo", emoji: "🍔", syllables: ["gor", "do"], targetIdx: 0, options: ["gor", "gro"] },
        { word: "norma", emoji: "📜", syllables: ["nor", "ma"], targetIdx: 0, options: ["nor", "ron"] },
        { word: "pardo", emoji: "🐻", syllables: ["par", "do"], targetIdx: 0, options: ["par", "pra"] },
        { word: "verde", emoji: "💚", syllables: ["ver", "de"], targetIdx: 0, options: ["ver", "vre"] },
        { word: "corto", emoji: "✂️", syllables: ["cor", "to"], targetIdx: 0, options: ["cor", "cro"] },
        { word: "largo", emoji: "📏", syllables: ["lar", "go"], targetIdx: 0, options: ["lar", "ral"] },
        { word: "burla", emoji: "😜", syllables: ["bur", "la"], targetIdx: 0, options: ["bur", "bru"] },
        { word: "forma", emoji: "📦", syllables: ["for", "ma"], targetIdx: 0, options: ["for", "fro"] },
        { word: "manta", emoji: "🛌", syllables: ["man", "ta"], targetIdx: 0, options: ["man", "nam"] },
        { word: "canto", emoji: "🎤", syllables: ["can", "to"], targetIdx: 0, options: ["can", "nac"] },
        { word: "punto", emoji: "📍", syllables: ["pun", "to"], targetIdx: 0, options: ["pun", "pnu"] },
        { word: "bolso", emoji: "👜", syllables: ["bol", "so"], targetIdx: 0, options: ["bol", "blo"] },
        { word: "culto", emoji: "🏛️", syllables: ["cul", "to"], targetIdx: 0, options: ["cul", "clu"] },
        { word: "bulto", emoji: "🎒", syllables: ["bul", "to"], targetIdx: 0, options: ["bul", "blu"] }
    ],
    mitad: [
        { word: "elefante", emoji: "🐘", syllables: ["e", "le", "fan", "te"], targetIdx: 2, options: ["fan", "fa"] },
        { word: "contento", emoji: "😊", syllables: ["con", "ten", "to"], targetIdx: 1, options: ["ten", "net"] },
        { word: "descansar", emoji: "😴", syllables: ["des", "can", "sar"], targetIdx: 1, options: ["can", "acn"] },
        { word: "manzana", emoji: "🍎", syllables: ["man", "za", "na"], targetIdx: 0, options: ["man", "na"] },
        { word: "ventana", emoji: "🪟", syllables: ["ven", "ta", "na"], targetIdx: 0, options: ["ven", "ne"] },
        { word: "garganta", emoji: "🧣", syllables: ["gar", "gan", "ta"], targetIdx: 1, options: ["gan", "na"] },
        { word: "serpiente", emoji: "🐍", syllables: ["ser", "pien", "te"], targetIdx: 1, options: ["pien", "pe"] },
        { word: "bufanda", emoji: "🧣", syllables: ["bu", "fan", "da"], targetIdx: 1, options: ["fan", "fa"] },
        { word: "pintura", emoji: "🎨", syllables: ["pin", "tu", "ra"], targetIdx: 0, options: ["pin", "pi"] },
        { word: "lámpara", emoji: "💡", syllables: ["lám", "pa", "ra"], targetIdx: 0, options: ["lám", "la"] },
        { word: "cáscara", emoji: "🍌", syllables: ["cás", "ca", "ra"], targetIdx: 0, options: ["cás", "ca"] },
        { word: "máscara", emoji: "🎭", syllables: ["más", "ca", "ra"], targetIdx: 0, options: ["más", "ma"] },
        { word: "fósforo", emoji: "🔥", syllables: ["fós", "fo", "ro"], targetIdx: 0, options: ["fós", "fo"] },
        { word: "cántaro", emoji: "🏺", syllables: ["cán", "ta", "ro"], targetIdx: 0, options: ["cán", "ca"] },
        { word: "paraguas", emoji: "☂️", syllables: ["pa", "ra", "guas"], targetIdx: 2, options: ["guas", "gu"] },
        { word: "pimiento", emoji: "🫑", syllables: ["pi", "mien", "to"], targetIdx: 1, options: ["pi", "mi"] },
        { word: "invierno", emoji: "❄️", syllables: ["in", "vier", "no"], targetIdx: 1, options: ["vier", "vi"] },
        { word: "estante", emoji: "📚", syllables: ["es", "tan", "te"], targetIdx: 1, options: ["tan", "ta"] },
        { word: "volante", emoji: "🎡", syllables: ["vo", "lan", "te"], targetIdx: 1, options: ["lan", "la"] },
        { word: "picante", emoji: "🌶️", syllables: ["pi", "can", "te"], targetIdx: 1, options: ["can", "ca"] }
    ],
    final: [
        { word: "pincel", emoji: "🖌️", syllables: ["pin", "cel"], targetIdx: 1, options: ["cel", "cle"] },
        { word: "tambor", emoji: "🥁", syllables: ["tam", "bor"], targetIdx: 1, options: ["bor", "bro"] },
        { word: "pastor", emoji: "🐑", syllables: ["pas", "tor"], targetIdx: 1, options: ["tor", "tro"] },
        { word: "carril", emoji: "🛤️", syllables: ["ca", "rril"], targetIdx: 1, options: ["rril", "rli"] },
        { word: "barril", emoji: "🛢️", syllables: ["ba", "rril"], targetIdx: 1, options: ["rril", "rli"] },
        { word: "motor", emoji: "⚙️", syllables: ["mo", "tor"], targetIdx: 1, options: ["tor", "tro"] },
        { word: "color", emoji: "🌈", syllables: ["co", "lor"], targetIdx: 1, options: ["lor", "lro"] },
        { word: "valor", emoji: "💎", syllables: ["va", "lor"], targetIdx: 1, options: ["lor", "lro"] },
        { word: "calor", emoji: "🌡️", syllables: ["ca", "lor"], targetIdx: 1, options: ["lor", "lro"] },
        { word: "sabor", emoji: "👅", syllables: ["sa", "bor"], targetIdx: 1, options: ["bor", "bro"] },
        { word: "labor", emoji: "👷", syllables: ["la", "bor"], targetIdx: 1, options: ["bor", "bro"] },
        { word: "favor", emoji: "🙏", syllables: ["fa", "vor"], targetIdx: 1, options: ["vor", "vro"] },
        { word: "tenor", emoji: "👨‍🎤", syllables: ["te", "nor"], targetIdx: 1, options: ["nor", "nro"] },
        { word: "vapor", emoji: "💨", syllables: ["va", "por"], targetIdx: 1, options: ["por", "pro"] },
        { word: "sudor", emoji: "💦", syllables: ["su", "dor"], targetIdx: 1, options: ["dor", "dro"] },
        { word: "rigor", emoji: "📏", syllables: ["ri", "gor"], targetIdx: 1, options: ["gor", "gro"] },
        { word: "humor", emoji: "🤡", syllables: ["hu", "mor"], targetIdx: 1, options: ["mor", "mro"] },
        { word: "temor", emoji: "😨", syllables: ["te", "mor"], targetIdx: 1, options: ["mor", "mro"] },
        { word: "honor", emoji: "🎖️", syllables: ["ho", "nor"], targetIdx: 1, options: ["nor", "nro"] },
        { word: "pastor", emoji: "✝️", syllables: ["pas", "tor"], targetIdx: 1, options: ["tor", "tro"] }
    ]
  }
};
